### ISSUE TITLE
Erros when testing 

### ISSUE THREAD

**Issue by papercut-linkin** [mihdalal/raps#9]
Hello and thanks for your sharing of this amazing work!
I'm trying to run the code you recommended
`python experiments/kitchen/dreamer/dreamer_v2_single_task_primitives.py --mode here_no_doodad  --env microwave
`
however, i found an error which is not mentioned previously in other issues
```
2022-06-08 17:39:37.331497 CST | Variant:
2022-06-08 17:39:37.332199 CST | {
  "env_name": "microwave",
  "algorithm": "DreamerV2",
  "version": "normal",
  "replay_buffer_size": 500000,
  "algorithm_kwargs": {
    "num_epochs": 250,
    "num_eval_steps_per_epoch": 30,
    "min_num_steps_before_training": 2500,
    "num_pretrain_steps": 100,
    "max_path_length": 5,
    "batch_size": 417,
    "num_expl_steps_per_train_loop": 30,
    "num_train_loops_per_epoch": 40,
    "num_trains_per_train_loop": 10
  },
  "use_raw_actions": false,
  "env_suite": "kitchen",
  "pass_render_kwargs": true,
  "save_video": true,
  "env_kwargs": {
    "dense": false,
    "image_obs": true,
    "action_scale": 1.4,
    "use_workspace_limits": true,
    "control_mode": "primitives",
    "usage_kwargs": {
      "use_dm_backend": true,
      "use_raw_action_wrappers": false,
      "use_image_obs": true,
      "max_path_length": 5,
      "unflatten_images": false
    },
    "image_kwargs": {}
  },
  "actor_kwargs": {
    "discrete_continuous_dist": true,
    "init_std": 0.0,
    "num_layers": 4,
    "min_std": 0.1,
    "dist": "tanh_normal_dreamer_v1"
  },
  "vf_kwargs": {
    "num_layers": 3
  },
  "model_kwargs": {
    "model_hidden_size": 400,
    "stochastic_state_size": 50,
    "deterministic_state_size": 200,
    "embedding_size": 1024,
    "rssm_hidden_size": 200,
    "reward_num_layers": 2,
    "pred_discount_num_layers": 3,
    "gru_layer_norm": true,
    "std_act": "sigmoid2"
  },
  "trainer_kwargs": {
    "adam_eps": 1e-05,
    "discount": 0.8,
    "lam": 0.95,
    "forward_kl": false,
    "free_nats": 1.0,
    "pred_discount_loss_scale": 10.0,
    "kl_loss_scale": 0.0,
    "transition_loss_scale": 0.8,
    "actor_lr": 8e-05,
    "vf_lr": 8e-05,
    "world_model_lr": 0.0003,
    "reward_loss_scale": 2.0,
    "use_pred_discount": true,
    "policy_gradient_loss_scale": 1.0,
    "actor_entropy_loss_schedule": "1e-4",
    "target_update_period": 100,
    "detach_rewards": false,
    "imagination_horizon": 5
  },
  "num_expl_envs": 5,
  "num_eval_envs": 1,
  "expl_amount": 0.3,
  "seed": "23764",
  "exp_id": "0",
  "exp_prefix": "06-08-test",
  "instance_type": "None",
  "exp_name": "06-08-test_2022_06_08_17_39_37_0000--s-23764"
}
/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/mujoco_vec_wrappers.py", line 72, in _worker
    env = env_fn_wrapper.var()
  File "/home/lwt/github_test/raps/rlkit/rlkit/torch/model_based/dreamer/experiments/kitchen_dreamer.py", line 42, in <lambda>
    lambda: primitives_make_env.make_env(env_suite, env_name, env_kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/primitives_make_env.py", line 129, in make_env
    env = make_base_kitchen_env(env_name, env_kwargs_new)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/primitives_make_env.py", line 99, in make_base_kitchen_env
    env = ALL_KITCHEN_ENVIRONMENTS[env_class](**env_kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/kitchen_envs.py", line 36, in __init__
    super(KitchenBase, self).__init__(**kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 771, in __init__
    super(KitchenTaskRelaxV1, self).__init__(**kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 216, in __init__
    distance=2.2, lookat=[-0.2, 0.5, 2.0], azimuth=70, elevation=-35
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/robot_env.py", line 82, in __init__
    model_path, frame_skip, camera_settings=camera_settings
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/mujoco_env.py", line 67, in __init__
    camera_settings=camera_settings,
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/simulation/sim_robot.py", line 68, in __init__
    self.sim = dm_mujoco.Physics.from_xml_path(model_file)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 443, in from_xml_path
    return cls.from_model(model)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 407, in from_model
    return cls(data)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 122, in __init__
    self._reload_from_data(data)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 389, in _reload_from_data
    data=index.struct_indexer(self.data, 'mjdata', axis_indexers),)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/index.py", line 623, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjData' object has no attribute 'qacc_unc'
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/mujoco_vec_wrappers.py", line 72, in _worker
    env = env_fn_wrapper.var()
  File "/home/lwt/github_test/raps/rlkit/rlkit/torch/model_based/dreamer/experiments/kitchen_dreamer.py", line 42, in <lambda>
    lambda: primitives_make_env.make_env(env_suite, env_name, env_kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/primitives_make_env.py", line 129, in make_env
    env = make_base_kitchen_env(env_name, env_kwargs_new)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/primitives_make_env.py", line 99, in make_base_kitchen_env
    env = ALL_KITCHEN_ENVIRONMENTS[env_class](**env_kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/kitchen_envs.py", line 36, in __init__
    super(KitchenBase, self).__init__(**kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 771, in __init__
    super(KitchenTaskRelaxV1, self).__init__(**kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 216, in __init__
    distance=2.2, lookat=[-0.2, 0.5, 2.0], azimuth=70, elevation=-35
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/robot_env.py", line 82, in __init__
    model_path, frame_skip, camera_settings=camera_settings
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/mujoco_env.py", line 67, in __init__
    camera_settings=camera_settings,
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/simulation/sim_robot.py", line 68, in __init__
    self.sim = dm_mujoco.Physics.from_xml_path(model_file)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 443, in from_xml_path
    return cls.from_model(model)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 407, in from_model
    return cls(data)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 122, in __init__
    self._reload_from_data(data)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 389, in _reload_from_data
    data=index.struct_indexer(self.data, 'mjdata', axis_indexers),)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/index.py", line 623, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjData' object has no attribute 'qacc_unc'
Process SpawnProcess-5:
Traceback (most recent call last):
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/mujoco_vec_wrappers.py", line 72, in _worker
    env = env_fn_wrapper.var()
  File "/home/lwt/github_test/raps/rlkit/rlkit/torch/model_based/dreamer/experiments/kitchen_dreamer.py", line 42, in <lambda>
    lambda: primitives_make_env.make_env(env_suite, env_name, env_kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/primitives_make_env.py", line 129, in make_env
    env = make_base_kitchen_env(env_name, env_kwargs_new)
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/primitives_make_env.py", line 99, in make_base_kitchen_env
    env = ALL_KITCHEN_ENVIRONMENTS[env_class](**env_kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/kitchen_envs.py", line 36, in __init__
    super(KitchenBase, self).__init__(**kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 771, in __init__
    super(KitchenTaskRelaxV1, self).__init__(**kwargs)
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/franka/kitchen_multitask_v0.py", line 216, in __init__
    distance=2.2, lookat=[-0.2, 0.5, 2.0], azimuth=70, elevation=-35
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/robot_env.py", line 82, in __init__
    model_path, frame_skip, camera_settings=camera_settings
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/mujoco_env.py", line 67, in __init__
    camera_settings=camera_settings,
  File "/home/lwt/github_test/raps/d4rl/d4rl/kitchen/adept_envs/simulation/sim_robot.py", line 68, in __init__
    self.sim = dm_mujoco.Physics.from_xml_path(model_file)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 443, in from_xml_path
    return cls.from_model(model)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 407, in from_model
    return cls(data)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 122, in __init__
    self._reload_from_data(data)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 389, in _reload_from_data
    data=index.struct_indexer(self.data, 'mjdata', axis_indexers),)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/site-packages/dm_control/mujoco/index.py", line 623, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjData' object has no attribute 'qacc_unc'
Traceback (most recent call last):
  File "experiments/kitchen/dreamer/dreamer_v2_single_task_primitives.py", line 139, in <module>
    exp_id=exp_id,
  File "/home/lwt/github_test/raps/rlkit/rlkit/launchers/launcher_util.py", line 590, in run_experiment
    return run_experiment_here(method_call, **run_experiment_kwargs)
  File "/home/lwt/github_test/raps/rlkit/rlkit/launchers/launcher_util.py", line 168, in run_experiment_here
    return experiment_function(variant)
  File "/home/lwt/github_test/raps/rlkit/rlkit/torch/model_based/dreamer/experiments/kitchen_dreamer.py", line 45, in experiment
    expl_env = StableBaselinesVecEnv(env_fns=env_fns, start_method="fork")
  File "/home/lwt/github_test/raps/rlkit/rlkit/envs/mujoco_vec_wrappers.py", line 134, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/lwt/anaconda3/envs/raps/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```
I searched google for answers to solve the MjData problem, but nothing was found.
I wonder if you can give me some advice, thanks for your selfless assistance!

**Comment by mihdalal** [comment]
Hi,
Sorry for the late response. I haven't seen this error before but I would suspect it is due to mujoco / dm control version issue.
1. what version of mujoco/dm control do you have?
2. does this issue occur when you run with metaworld/robosuite?

**Comment by Kaiwen-Hong** [comment]
I encountered this problem and found it's the problem of mujoco version. Note as the sixth update in Mujoco 2.2 says, "mjData fields qfrc_unc (unconstrained forces) and qacc_unc (unconstrained accelerations) were renamed qfrc_smooth and qacc_smooth, respectively".

**Comment by quangbk2010** [comment]
Hi, I have the same problem. May i ask what is the version of mujoco and mujoco-py in your settings? 
Thank you!

**Comment by ZhenfengSu** [comment]
> Hi, I have the same problem. May i ask what is the version of mujoco and mujoco-py in your settings? Thank you!

Hi，I have the same problem，have you solved this problem？
